### ISSUE TITLE
Use Swift Package Manager instead of CocoaPods

### ISSUE THREAD

**Issue by fbernutz** [spacepandas/cineaste-ios#140]
## Tasks

- [ ] Update `README.md` on [how to build](https://github.com/spacepandas/cineaste-ios#how-to-build) the app
- [ ] Update `.gitignore`
- [ ] What to do with `swiftlint`? (Maybe use a precommit hook with [`Komondor`](https://github.com/shibapm/Komondor), see this as [example](https://artsy.github.io/blog/2019/01/05/its-time-to-use-spm/))
- [ ] Update GithubAction Workflow (no need to install Pods anymore but resolve Packages?)
- [ ] Update `update-dependencies.sh` 
- [ ] How to update License in App and Settings of App? This is generated by CocoaPods right now.

**Comment by xavierLowmiller** [comment]
> What to do with swiftlint?

Why not just drop the pod?

It'll run locally for people who have SwiftLint installed, and it's skipped for all others.

It's run on CI, so pull requests will always be clean.
